<?php
$message = "<!DOCTYPE html>";
$message .= "<html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">";
$message .= "<head>";
$message .= "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />";
$message .= "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />";
$message .= "<meta name=\"format-detection\" content=\"telephone=no\" />";
$message .= "<title>New Contact Form Submission </title>";
$message .= "<style type=\"text/css\">
body {
width: 100% !important;
-webkit-text-size-adjust: 100%;
-ms-text-size-adjust: 100%;
margin: 0;
padding: 0;
}

.ExternalClass {
width: 100%;
}

.ExternalClass,
.ExternalClass span,
.ExternalClass font,
.ExternalClass td,
.ExternalClass div {
line-height: 100%;
}

.ExternalClass p {
line-height: inherit;
}

#body-layout {
margin: 0;
padding: 0;
width: 100% !important;
line-height: 100% !important;
}

img {
display: block;
outline: none;
text-decoration: none;
-ms-interpolation-mode: bicubic;
width: 100%;
}

a img {
border: none;
}

table td {
border-collapse: collapse;
}

table {
border-collapse: collapse;
mso-table-lspace: 0pt;
mso-table-rspace: 0pt;
}

a {
color: inherit;
outline: none;
text-decoration: none;
}
</style>";
$message .= "<style type=\"text/css\">
[style*=\"Lato\"] {
font-family: \"Lato\", \"Trebuchet MS\", Helvetica, sans-serif !important;
}

@media only screen and (max-width: 414px) {

div[class=\"block\"] {
width: 100% !important;
max-width: 375px !important;
}

div[class=\"full-block\"] {
width: 100% !important;
max-width: none !important;
}

table[class=\"full-width\"] {
width: 100% !important;
}
}
</style>";
$message .= "<link href=\"https://fonts.googleapis.com/css?family=Lato:400,700,700italic\" rel=\"stylesheet\" type=\"text/css\"/>";
$message .= "</head>";
$message .= "<body id=\"body-layout\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"background: #00003e;\">";
$message .= "<table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td width=\"800\" align=\"center\" valign=\"top\" style=\"background: #ffffff;\">";
$message .= "<!--Brand-->";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"padding: 0 20px;\">";
$message .= "<table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td width=\"139\" align=\"center\" valign=\"top\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td height=\"31\" style=\"height: 30px; line-height:30px;\"></td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"line-height: 0px !important;\">";
$message .= "<a style=\"text-decoration: none; display: block;\"
href=\"$this->m_base_url\">";
$message .= "<img src=\"{$this->m_image_directory}logo/wheelies-logo.png\" alt=\"Wheelies logo\" width=\"100%\" style=\"width: 100%; max-width: 100%;\" />";
$message .= "</a>";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td height=\"30\" style=\"height: 30px; line-height: 30px;\"></td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";

$message .= "<!--Content Section-->";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"padding: 0 20px;\">";
$message .= "<table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td width=\"620\" align=\"center\" valign=\"top\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td height=\"45\" style=\"height: 45px; line-height:45px;\"></td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\"";
$message .= "style=\"color: #434345; font-family: \"Trebuchet MS\", Helvetica, sans-serif, \"Lato\", sans-serif; font-size: 30px; ";
$message .= "mso-line-height-rule: exactly; line-height: 36px; font-weight: 700;\">";
$message .= "Hello Wheelies Bikes,";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td height=\"16\" style=\"height: 16px; line-height:16px;\"></td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td height=\"40\" style=\"height: 40px; line-height:40px;\"></td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\"";
$message .= "style=\"color: #ff0800; font-family: \"Trebuchet MS\", Helvetica, sans-serif, \"Lato\", sans-serif; font-size: 16px;";
$message .= "mso-line-height-rule: exactly; line-height: 24px; font-weight: 400;\">";
$message .= "<p>";
$message .= "A new contact has been received from your website.";
$message .= "</p>";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td height=\"63\" style=\"height: 63px; line-height:63px;\"></td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";

$message .= "<!--Section Looking excellent on any device-->";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"background: #65abe1;\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"padding: 0 20px;\">";
$message .= "<table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td width=\"560\" align=\"center\" valign=\"top\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td height=\"58\" style=\"height: 58px; line-height:58px;\"></td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\"";
$message .= "style=\"color: #ffffff; font-family: Arial, sans-serif; font-size: 35px; mso-line-height-rule: exactly line-height: 42px; font-weight: 400;\">";
$message .= "Enquiry Details";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td height=\"27\" style=\"height: 27px; line-height:27px;\"></td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"line-height: 0px !important;\">";
$message .= "Customer Information";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td height=\"27\" style=\"height: 27px; line-height:27px;\"></td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"line-height: 0px !important;\">";
$message .= "Name: " . $this->_contact_form_first_name . " " .
$this->_contact_form_last_name;
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td height=\"27\" style=\"height: 27px; line-height:27px;\"></td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"line-height: 0px !important;\">";
$message .= "Email: " . $this->_contact_form_email;
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td height=\"27\" style=\"height: 27px; line-height:27px;\"></td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"line-height: 0px !important;\">";
$message .= "Phone Number: " . $this->_contact_form_phone_number;
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td height=\"27\" style=\"height: 27px; line-height:27px;\"></td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"line-height: 0px !important;\">";
$message .= "Message: " . $this->_contact_form_message;
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td height=\"27\" style=\"height: 27px; line-height:27px;\"></td>";
$message .= "</tr>";

$message .= "<tr>";
$message .= "<td height=\"22\" style=\"height: 22px; line-height:22px;\"></td>";
$message .= "</tr>";

$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";

$message .= "<!--Get in touch with us-->";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"background: #000000;\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"background-image: url({$this->m_image_directory}about-page-top-banner.jpg); background-repeat: no-repeat; background-size:cover; background-position: 50% 0;\" background=\"{$this->m_image_directory}about-page-top-banner.jpg\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"padding: 0 20px;\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td height=\"93\" style=\"height: 93px; line-height:93px;\"></td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"color: #ffffff; font-family: Arial, sans-serif; font-size: 24px; mso-line-height-rule: exactly; line-height: 28px; font-weight: 400;\">";
$message .= "Follow us on social media";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td height=\"17\" style=\"height: 17px; line-height:17px;\"></td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"color: #ffffff; font-family: Arial, sans-serif; font-size: 35px; mso-line-height-rule: exactly; line-height: 42px; font-weight: 400;\">";
$message .= "Visit our social media accounts";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td height=\"19\" style=\"height: 19px; line-height:19px;\"></td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\">";
$message .= "<table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td width=\"210\" align=\"center\" valign=\"top\" style=\"font-size: 0px !important;\">";
$message .= "<!--[if (gte mso 9)|(IE)]>";
$message .= "<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">";
$message .= "<tr>";
$message .= "<![endif]-->";
$message .= "<!--[if (gte mso 9)|(IE)]>";
$message .= "<td width=\"70\" align=\"center\" valign=\"top\" style=\"padding: 0 0 0 0;\">";
$message .= "<![endif]-->";
$message .= "<div style=\"width: 100%; display: inline-block; vertical-align: top; font-size: normal; max-width: 70px;\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"padding: 0 10px;\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td height=\"15\" style=\"height: 15px; line-height:15px;\">";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"line-height: 0px !important;\">";
$message .= "<a style=\"text-decoration: none; display: inline-block;\" href=\"https://www.facebook.com/wheelieserith\">";
$message .= "<img src=\"{$this->m_image_directory}facebook-icon.png\" alt=\"Faceboobk icon\" width=\"50\"/>";
$message .= "</a>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</div>";
$message .= "<!--[if (gte mso 9)|(IE)]></td><![endif]-->";
$message .= "<!--[if (gte mso 9)|(IE)]>";
$message .= "<td width=\"70\" align=\"center\" valign=\"top\" style=\"padding: 0 0 0 0;\">";
$message .= "<![endif]-->";
$message .= "<div style=\"width: 100%; display: inline-block; vertical-align: top; font-size: normal; max-width: 70px;\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"padding: 0 10px;\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td height=\"15\" style=\"height: 15px; line-height:15px;\">";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"line-height: 0px !important;\">";
$message .= "<a style=\"text-decoration: none; display: inline-block;\"";
$message .= " href=\"https://www.instagram.com/wheelies_bikes\">";
$message .= "<img src=\"{$this->m_image_directory}instagram-icon.png\"";
$message .= " alt=\"Instagram icon\" width=\"50\" />";
$message .= "</a>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</div>";
$message .= "<!--[if (gte mso 9)|(IE)]></td><![endif]-->";
$message .= "<!--[if (gte mso 9)|(IE)]>";
$message .= "<td width=\"70\" align=\"center\" valign=\"top\" style=\"padding: 0 0 0 0;\">";
$message .= "<![endif]-->";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td height=\"83\" style=\"height: 83px; line-height:83px;\"></td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\">";
$message .= "<table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td width=\"680\" align=\"center\" valign=\"top\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"padding: 0 20px;\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td height=\"77\" style=\"height: 77px; line-height:77px;\"></td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"color: #4eb7fe; font-family: Arial, sans-serif; font-size: 24px; mso-line-height-rule: exactly; line-height: 28px; font-weight: 400;\">";
$message .= "Still have Questions? Contact Us using any of the following ways.";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td height=\"16\" style=\"height: 16px; line-height:16px;\"></td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\"";
$message .= " style=\"color: #333333; font-family: Arial, sans-serif; font-size: 35px; mso-line-height-rule: exactly; line-height: 42px; font-weight: 400;\">";
$message .= "Get in touch with Us";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td height=\"15\" style=\"height: 15px; line-height:15px;\"></td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"font-size: 0px !important;\">";
$message .= "<!--[if (gte mso 9)|(IE)]>";
$message .= "<td width=\"440\" align=\"center\" valign=\"top\" style=\"padding: 0 0 0 0;\">";
$message .= "<![endif]-->";
$message .= "<div style=\"width: 100%; display: inline-block; vertical-align: top; font-size: normal; max-width: 440px;\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"padding: 0 20px;\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td height=\"33\" style=\"height: 33px; line-height:33px;\">";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\"";
$message .= " cellspacing=\"0\" border=\"0\" >";
$message .= "<tr>";
$message .= "<td width=\"83\" align=\"center\" valign=\"top\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"line-height: 0px !important;\">";
$message .= "<img src=\"{$this->m_image_directory}icon1.png\" alt=\"icon1\" width=\"83\" />";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "<td align=\"center\" valign=\"top\" style=\"padding: 0 0 0 20px;\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td height=\"2\" style=\"height: 2px; line-height:2px;\">";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"left\" valign=\"top\" style=\"color: #333333; font-family: Arial, sans-serif; font-size: 20px; mso-line-height-rule: exactly; line-height: 24px; font-weight: 400;\">";
$message .= "Address:";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td height=\"2\" style=\"height: 2px; line-height:2px;\">";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"left\" valign=\"top\" style=\"color: #4eb7fe; font-family: Arial, sans-serif; font-size: 16px; mso-line-height-rule: exactly; line-height: 26px; font-weight: 400;\">";
$message .= "239, Bexley Road Erith, ";
$message .= "</br>Kent DA8 3EX";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</div>";
$message .= "<!--[if (gte mso 9)|(IE)]></td><![endif]-->";
$message .= "<!--[if (gte mso 9)|(IE)]>";
$message .= "<td width=\"440\" align=\"center\" valign=\"top\" style=\"padding: 0 0 0 0;\">";
$message .= "<![endif]-->";
$message .= "<div style=\"width: 100%; display: inline-block; vertical-align: top; font-size: normal; max-width: 440px;\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"padding: 0 20px;\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td height=\"33\" style=\"height: 33px; line-height:33px;\">";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td width=\"83\" align=\"center\" valign=\"top\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"line-height: 0px !important;\">";
$message .= "<img src=\"{$this->m_image_directory}icon2.png\" alt=\"icon2\" width=\"83\"/>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "<td align=\"center\" valign=\"top\" style=\"padding: 0 0 0 20px;\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td height=\"2\" style=\"height: 2px; line-height:2px;\">";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"left\" valign=\"top\" style=\"color: #333333; font-family: Arial, sans-serif; font-size: 20px; mso-line-height-rule: exactly; line-height: 24px; font-weight: 400;\">";
$message .= "Phone number:";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td height=\"2\" style=\"height: 2px; line-height:2px;\">";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"left\" valign=\"top\" style=\"color: #4eb7fe; font-family: Arial, sans-serif; font-size: 16px; mso-line-height-rule: exactly; line-height: 26px; font-weight: 400;\">";
$message .= "01322 338625";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</div>";
$message .= "<!--[if (gte mso 9)|(IE)]></td><![endif]-->";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"font-size: 0px !important;\">";
$message .= "<!--[if (gte mso 9)|(IE)]>";
$message .= "<td width=\"440\" align=\"center\" valign=\"top\" style=\"padding: 0 0 0 0;\">";
$message .= "<![endif]-->";
$message .= "<div style=\"width: 100%; display: inline-block; vertical-align: top; font-size: normal; max-width: 440px;\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"padding: 0 20px;\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td height=\"33\" style=\"height: 33px; line-height:33px;\">";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td width=\"83\" align=\"center\" valign=\"top\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"line-height: 0px !important;\">";
$message .= "<img src=\"{$this->m_image_directory}icon3.png\" alt=\"icon3\" width=\"83\" />";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "<td align=\"center\" valign=\"top\"";
$message .= "style=\"padding: 0 0 0 20px;\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td height=\"16\" style=\"height: 16px; line-height:16px;\">";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"left\" valign=\"top\" style=\"color: #333333; font-family: Arial, sans-serif; font-size: 20px; mso-line-height-rule: exactly; line-height: 24px; font-weight: 400;\">";
$message .= "Email:";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td height=\"2\" style=\"height: 2px; line-height:2px;\">";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"left\" valign=\"top\" style=\"color: #4eb7fe; font-family: Arial, sans-serif; font-size: 16px; mso-line-height-rule: exactly; line-height:26px; font-weight: 400;\">";
$message .= "<span style=\"color: #4eb7fe;\">";
$message .= "<a style=\"text-decoration: none; color: #4eb7fe;\" href=\"mailto:info@wheeliesbikes.co.uk\">";
$message .= "info@wheeliesbikes.co.uk";
$message .= "</a>";
$message .= "</span>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</div>";
$message .= "<!--[if (gte mso 9)|(IE)]></td><![endif]-->";
$message .= "<!--[if (gte mso 9)|(IE)]>";
$message .= "<td width=\"440\" align=\"center\" valign=\"top\" style=\"padding: 0 0 0 0;\"><![endif]-->";
$message .= "<div style=\"width: 100%; display: inline-block; vertical-align: top; font-size: normal; max-width: 440px;\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"padding: 0 20px;\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td height=\"33\" style=\"height: 33px; line-height:33px;\">";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td width=\"83\" align=\"center\" valign=\"top\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td align=\"center\" valign=\"top\" style=\"line-height: 0px !important;\">";
$message .= "<img src=\"{$this->m_image_directory}icon4.png\" alt=\"icon4\" width=\"83\" />";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "<td align=\"center\" valign=\"top\" style=\"padding: 0 0 0 20px;\">";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td height=\"16\" style=\"height: 16px; line-height:16px;\">";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"left\" valign=\"top\" style=\"color: #333333; font-family: Arial, sans-serif; font-size: 20px; mso-line-height-rule: exactly; line-height: 24px; font-weight: 400;\">";
$message .= "We are open:";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td height=\"2\" style=\"height: 2px; line-height:2px;\">";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"left\" valign=\"top\" style=\"color: #4eb7fe; font-family: Arial, sans-serif; font-size: 16px; mso-line-height-rule: exactly; line-height: 26px; font-weight: 400;\">";
$message .= "Mon - Sat: 9:00 AM - 17:30 ";
$message .= "</td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td align=\"left\" valign=\"top\" style=\"color: #4eb7fe; font-family: Arial, sans-serif; font-size: 16px; mso-line-height-rule: exactly; line-height: 26px; font-weight: 400;\">";
$message .= "Sun - 11:00 AM - 15:00 ";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</div>";
$message .= "<!--[if (gte mso 9)|(IE)]></td><![endif]-->";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td height=\"70\" style=\"height: 70px; line-height:70px;\"></td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";

$message .= "<table width=\"100%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
$message .= "<tr>";
$message .= "<td height=\"12\" style=\"height: 12px; line-height:12px;\"></td>";
$message .= "</tr>";
$message .= "<tr>";
$message .= "<td height=\"12\" style=\"height: 12px; line-height:12px;\"></td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</td>";
$message .= "</tr>";
$message .= "</table>";
$message .= "</body>";
$message .= "</html>";
