<?php
$body ='<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"';
$body.=' "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">';
$body.='<html xmlns="http://www.w3.org/1999/xhtml">';
$body.='<head>';
$body.='<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />';
$body.='<meta name="viewport" content="width=device-width, initial-scale=1.0" />';
$body.='<meta name="format-detection" content="telephone=no" />';
$body.='<title>Responsive E-mail Template</title>';
$body.='<style type="text/css">
body {
width: 100% !important;
-webkit-text-size-adjust: 100%;
-ms-text-size-adjust: 100%;
margin: 0;
padding: 0;
}

.ExternalClass {
width: 100%;
}

.ExternalClass,
.ExternalClass span,
.ExternalClass font,
.ExternalClass td,
.ExternalClass div {
line-height: 100%;
}

.ExternalClass p {
line-height: inherit;
}

#body-layout {
margin: 0;
padding: 0;
width: 100% !important;
line-height: 100% !important;
}

img {
display: block;
outline: none;
text-decoration: none;
-ms-interpolation-mode: bicubic;
}

a img {
border: none;
}

table td {
border-collapse: collapse;
}

table {
border-collapse: collapse;
mso-table-lspace: 0pt;
mso-table-rspace: 0pt;
}

a {
color: inherit;
outline: none;
text-decoration: none;
}
</style>';
$body.= ' <style type="text/css">
[style*="Lato"] {
font-family: "Lato", "Trebuchet MS", Helvetica, sans-serif !important;
}

@media only screen and (max-width: 414px) {

div[class="block"] {
width: 100% !important;
max-width: 375px !important;
}

div[class="full-block"] {
width: 100% !important;
max-width: none !important;
}

table[class="full-width"] {
width: 100% !important;
}
}
</style>';
$body.'=<link href="https://fonts.googleapis.com/css?family=Lato:400,700,700italic" rel="stylesheet" type="text/css" />';
$body.='</head>';
$body.='<body id="body-layout">';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top" style="background: #00003e;">';
$body.='<table align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td width="800" align="center" valign="top" style="background: #ffffff;">';
$body.='<!--Brand-->';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top" style="padding: 0 20px;">';
$body.='<table align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td width="139" align="center" valign="top">';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td height="31" style="height: 30px; line-height:30px;"></td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="center" valign="top" style="line-height: 0px !important;">';
$body.='<a style="text-decoration: none; display: block;" href="<?php echo URL ?>">';
$body.='<img src="<"'.IMAGES.'"logo/wheelies-logo.png" alt="Wheelies logo" width="100%" style="width: 100%; max-width: $body.=100%;" />';
$body.='</a>';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td height="30" style="height: 30px; line-height: 30px;"></td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';

$body.='<!--section About Us-->';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top" style="padding: 0 20px;">';
$body.='<table align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td width="620" align="center" valign="top">';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td height="45" style="height: 45px; line-height:45px;"></td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="center" valign="top"';
$body.'=style="color: #434345; font-family: "Trebuchet MS", Helvetica, sans-serif, "Lato", sans-serif; font-size: 30px; ';$body.='mso-line-height-rule: exactly; line-height: 36px; font-weight: 700;">';
$body.='Hello .$user,';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td height="16" style="height: 16px; line-height:16px;"></td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td height="40" style="height: 40px; line-height:40px;"></td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="center" valign="top"';
$body.'=style="color: #ff0800; font-family: "Trebuchet MS", Helvetica, sans-serif, "Lato", sans-serif; font-size: 16px;';
$body.='mso-line-height-rule: exactly; line-height: 24px; font-weight: 400;">';
$body.='<p>';
$body.'=This email is an automatically generated response to your enquiry from our website. Please don\'t respond to this email.';
$body.='</p>';
$body.='</td>';
$body.='</tr>';
$body.'=';
$body.='<tr>';
$body.='<td height="63" style="height: 63px; line-height:63px;"></td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';

$body.='<!--Section Looking excellent on any device-->';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top" style="background: #65abe1;">';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top" style="padding: 0 20px;">';
$body.='<table align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td width="560" align="center" valign="top">';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td height="58" style="height: 58px; line-height:58px;"></td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="center" valign="top"';
$body.='style="color: #ffffff; font-family: Arial, sans-serif; font-size: 35px; mso-line-height-rule: exactly line-height: 42px; font-weight: 400;">';
$body.='You have enquired about the product below.';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td height="27" style="height: 27px; line-height:27px;"></td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="center" valign="top" style="line-height: 0px !important;"><img';
$body.='src="<?php echo IMAGES ?>products-images/frog-48-purple.jpg"';
$body.='alt="img" width="100%" style="width: 100%; max-width: 100%;" />';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td height="27" style="height: 27px; line-height:27px;"></td>';
$body.='</tr>';
$body.='<tr>';
$body.='<tr>';
$body.='<td align="center" valign="top" style="color: #ffffff; font-family: Arial, sans-serif; font-size: 35px; mso-line-height-rule: exactly; line-height: 42px; font-weight: 400;">';
$body.='Product Name: Frog 48';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="center" valign="top"';
$body.='style="color: #ffffff; font-family: Arial, sans-serif; font-size: 35px; mso-line-height-rule: exactly; line-height: 42px; font-weight: 400;">';
$body.='Product Price:£ 400.00';
$body.='</td>';
$body.='</tr>';
$body.='</tr>';
$body.='<tr>';
$body.='<td height="22" style="height: 22px; line-height:22px;"></td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';

$body.='<!--Like what we offer?-->';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top" style="background: #65abe1;">';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top"';
$body.='style="padding: 0 20px; background-image: url("'.IMAGES.'"slider-01.jpg); background-repeat: no-repeat; background-position: 50% 50%;"';
$body.='background="<"'.IMAGES.'"slider-01.jpg">';
$body.='<table align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td width="720" align="center" valign="top">';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td height="10" style="height: 10px; line-height:10px;"></td>';
$body.='</tr>';
$body.='</table>';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td align="left" valign="top" style="font-size: 0px !important;">';
$body.='<!--[if (gte mso 9)|(IE)]>';
$body.='<td width="340" align="center" valign="top" style="padding: 0 0 0 0;">';
$body.='<![endif]-->';
$body.='<div';
$body.='style="width: 100%; display: inline-block; vertical-align: top; font-size: normal; max-width: 340px;">';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0"';
$body.='border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top">';
$body.='<table align="right" cellpadding="0" cellspacing="0"';
$body.='border="0">';
$body.='<tr>';
$body.='<td width="302" align="center" valign="top">';
$body.='<table width="100%" align="center"';
$body.='cellpadding="0" cellspacing="0"';
$body.='border="0">';
$body.='<tr>';
$body.='<td height="42"';
$body.='style="height: 42px; line-height:42px;">';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="left" valign="top"';
$body.='style="color: #00003e; font-family: Arial, sans-serif; font-size: 35px; mso-line-height-rule: exactly; line-height: 42px; font-weight: 400;">';
$body.='Like';
$body.='what';
$body.='we';
$body.='offer?';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td height="12"';
$body.='style="height: 12px; line-height:12px;">';
$body.='</td>';
$body.='</tr>';
$body.='<tr style="background:#f6f6f6;">';
$body.='<td align="left" valign="top"';
$body.='style="color: #00003e; font-family: Arial, sans-serif; font-size: 24px; mso-line-height-rule: exactly; line-height: 40px; font-weight: 400;padding-left:15px; padding-right:15px;">';
$body.='Feel free';
$body.='to get in';
$body.='touch with';
$body.='us';
$body.='regarding';
$body.='all your';
$body.='bicycle';
$body.='needs.';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td height="18"';
$body.='style="height: 18px; line-height:18px;">';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</div>';
$body.='<!--[if (gte mso 9)|(IE)]></td><![endif]-->';
$body.='<!--[if (gte mso 9)|(IE)]>';
$body.='<td width="380" align="center" valign="top" style="padding: 0 0 0 0;">';
$body.='<![endif]-->';
$body.='<div';
$body.='style="width: 100%; display: inline-block; vertical-align: top; font-size: normal; max-width: 380px;">';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0"';
$body.='border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top">';
$body.='<table align="right" cellpadding="0" cellspacing="0"';
$body.='border="0">';
$body.='<tr>';
$body.='<td width="340" align="center" valign="top">';
$body.='<table width="100%" align="center"';
$body.='cellpadding="0" cellspacing="0"';
$body.='border="0">';
$body.='<tr>';
$body.='<td height="43"';
$body.='style="height: 43px; line-height:43px;">';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</div>';
$body.='<!--[if (gte mso 9)|(IE)]></td><![endif]-->';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td height="34" style="height: 34px; line-height:34px;"></td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';


$body.='<!--Get in touch with us-->';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top" style="background: #000000;">';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top"';
$body.='style="background-image: url(images/bgimg3.jpg); background-repeat: no-repeat; background-size:cover; background-position: 50% 0;"';
$body.='background="images/bgimg3.jpg">';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top" style="padding: 0 20px;">';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td height="93" style="height: 93px; line-height:93px;"></td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="center" valign="top"';
$body.='style="color: #ffffff; font-family: Arial, sans-serif; font-size: 24px; mso-line-height-rule: exactly; line-height: 28px; font-weight: 400;">';
$body.='Follow us on social media';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td height="17" style="height: 17px; line-height:17px;"></td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="center" valign="top"';
$body.='style="color: #ffffff; font-family: Arial, sans-serif; font-size: 35px; mso-line-height-rule: exactly; line-height: 42px; font-weight: 400;">';
$body.='Visit our social media accounts';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td height="19" style="height: 19px; line-height:19px;"></td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="center" valign="top">';
$body.='<table align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td width="210" align="center" valign="top"';
$body.='style="font-size: 0px !important;">';
$body.='<!--[if (gte mso 9)|(IE)]>';
$body.='<table width="100%" border="0" cellspacing="0" cellpadding="0" align="center">';
$body.='<tr><![endif]-->';
$body.='<!--[if (gte mso 9)|(IE)]>';
$body.='<td width="70" align="center" valign="top" style="padding: 0 0 0 0;">';
$body.='<![endif]-->';
$body.='<div';
$body.='style="width: 100%; display: inline-block; vertical-align: top; font-size: normal; max-width: 70px;">';
$body.='<table width="100%" align="center" cellpadding="0"';
$body.='cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top"';
$body.='style="padding: 0 10px;">';
$body.='<table width="100%" align="center"';
$body.='cellpadding="0" cellspacing="0"';
$body.='border="0">';
$body.='<tr>';
$body.='<td height="15"';
$body.='style="height: 15px; line-height:15px;">';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="center" valign="top"';
$body.='style="line-height: 0px !important;">';
$body.='<a style="text-decoration: none; display: inline-block;" href="https://www.facebook.com/wheelieserith">';
$body.='<img src=""'.IMAGES.'"facebook-icon.png" alt="Faceboobk icon" width="50" />';
$body.='</a>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</div>';
$body.='<!--[if (gte mso 9)|(IE)]></td><![endif]-->';
$body.='<!--[if (gte mso 9)|(IE)]>';
$body.='<td width="70" align="center" valign="top" style="padding: 0 0 0 0;">';
$body.='<![endif]-->';
$body.='<div';
$body.='style="width: 100%; display: inline-block; vertical-align: top; font-size: normal; max-width: 70px;">';
$body.='<table width="100%" align="center" cellpadding="0"';
$body.='cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top"';
$body.='style="padding: 0 10px;">';
$body.='<table width="100%" align="center"';
$body.='cellpadding="0" cellspacing="0"';
$body.='border="0">';
$body.='<tr>';
$body.='<td height="15"';
$body.='style="height: 15px; line-height:15px;">';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="center" valign="top" style="line-height: 0px !important;">';
$body.='<a style="text-decoration: none; display: inline-block;"';
$body.='href="https://www.instagram.com/wheelies_bikes">';
$body.='<img src=""'.IMAGES.'"instagram-icon.png"';
$body.='alt="Instagram icon"';
$body.='width="50" /></a>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</div>';
$body.='<!--[if (gte mso 9)|(IE)]></td><![endif]-->';
$body.='<!--[if (gte mso 9)|(IE)]>';
$body.='<td width="70" align="center" valign="top" style="padding: 0 0 0 0;">';
$body.='<![endif]-->';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td height="83" style="height: 83px; line-height:83px;"></td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top">';
$body.='<table align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td width="680" align="center" valign="top">';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top" style="padding: 0 20px;">';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td height="77" style="height: 77px; line-height:77px;"></td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="center" valign="top"';
$body.='style="color: #4eb7fe; font-family: Arial, sans-serif; font-size: 24px; mso-line-height-rule: exactly; line-height: 28px; font-weight: 400;">';
$body.='Still have Questions? Contact Us using any of the following ways.';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td height="16" style="height: 16px; line-height:16px;"></td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="center" valign="top"';
$body.='style="color: #333333; font-family: Arial, sans-serif; font-size: 35px; mso-line-height-rule: exactly; line-height: 42px; font-weight: 400;">';
$body.='Get in touch with Us';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td height="15" style="height: 15px; line-height:15px;"></td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top" style="font-size: 0px !important;">';
$body.='<!--[if (gte mso 9)|(IE)]>';
$body.='  <td width="440" align="center" valign="top" style="padding: 0 0 0 0;"><![endif]-->';
$body.='<div';
$body.='style="width: 100%; display: inline-block; vertical-align: top; font-size: normal; max-width: 440px;">';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top" style="padding: 0 20px;">';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0"';
$body.='border="0">';
$body.='<tr>';
$body.='<td height="33" style="height: 33px; line-height:33px;">';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="center" valign="top">';
$body.='<table width="100%" align="center" cellpadding="0"';
$body.='cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td width="83" align="center" valign="top">';
$body.='<table width="100%" align="center"';
$body.='cellpadding="0" cellspacing="0"';
$body.='border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top"';
$body.='style="line-height: 0px !important;">';
$body.='<img src="<?php echo IMAGES ?>icon1.png"';
$body.='alt="icon1" width="83" />';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='<td align="center" valign="top"';
$body.='style="padding: 0 0 0 20px;">';
$body.='<table width="100%" align="center"';
$body.='cellpadding="0" cellspacing="0"';
$body.='border="0">';
$body.='<tr>';
$body.='<td height="2"';
$body.='style="height: 2px; line-height:2px;">';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="left" valign="top"';
$body.='style="color: #333333; font-family: Arial, sans-serif; font-size: 20px; mso-line-height-rule: exactly; line-height: 24px; font-weight: 400;">';
$body.='Address:';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td height="2"';
$body.='style="height: 2px; line-height:2px;">';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="left" valign="top"';
$body.='style="color: #4eb7fe; font-family: Arial, sans-serif; font-size: 16px; mso-line-height-rule: exactly; line-height: 26px; font-weight: 400;">';
$body.='239, Bexley Road Erith, ';
$body.='</br>Kent DA8 3EX';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</div>';
$body.='<!--[if (gte mso 9)|(IE)]></td><![endif]-->';
$body.='<!--[if (gte mso 9)|(IE)]>';
$body.='<td width="440" align="center" valign="top" style="padding: 0 0 0 0;"><![endif]-->';
$body.='<div';
$body.='style="width: 100%; display: inline-block; vertical-align: top; font-size: normal; max-width: 440px;">';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top" style="padding: 0 20px;">';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0"';
$body.='border="0">';
$body.='<tr>';
$body.='<td height="33" style="height: 33px; line-height:33px;">';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="center" valign="top">';
$body.='<table width="100%" align="center" cellpadding="0"';
$body.='cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td width="83" align="center" valign="top">';
$body.='<table width="100%" align="center"';
$body.='cellpadding="0" cellspacing="0"';
$body.='border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top"';
$body.='style="line-height: 0px !important;">';
$body.='<img src="images/icon2.png"';
$body.='alt="icon2" width="83" />';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='<td align="center" valign="top"';
$body.='style="padding: 0 0 0 20px;">';
$body.='<table width="100%" align="center"';
$body.='cellpadding="0" cellspacing="0"';
$body.='border="0">';
$body.='<tr>';
$body.='<td height="2"';
$body.='style="height: 2px; line-height:2px;">';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="left" valign="top"';
$body.='style="color: #333333; font-family: Arial, sans-serif; font-size: 20px; mso-line-height-rule: exactly; line-height: 24px; font-weight: 400;">';
$body.='Phone number:';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td height="2"';
$body.='style="height: 2px; line-height:2px;">';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="left" valign="top"';
$body.='style="color: #4eb7fe; font-family: Arial, sans-serif; font-size: 16px; mso-line-height-rule: exactly; line-height: 26px; font-weight: 400;">';
$body.='01322 338625';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</div>';
$body.='<!--[if (gte mso 9)|(IE)]></td><![endif]-->';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top" style="font-size: 0px !important;">';
$body.='<!--[if (gte mso 9)|(IE)]>';
$body.='<td width="440" align="center" valign="top" style="padding: 0 0 0 0;"><![endif]-->';
$body.='<div';
$body.='style="width: 100%; display: inline-block; vertical-align: top; font-size: normal; max-width: 440px;">';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top" style="padding: 0 20px;">';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0"';
$body.='border="0">';
$body.='<tr>';
$body.='<td height="33" style="height: 33px; line-height:33px;">';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="center" valign="top">';
$body.='<table width="100%" align="center" cellpadding="0"';
$body.='cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td width="83" align="center" valign="top">';
$body.='<table width="100%" align="center"';
$body.='cellpadding="0" cellspacing="0"';
$body.='border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top"';
$body.='style="line-height: 0px !important;">';
$body.='<img src="images/icon3.png"';
$body.='alt="icon3" width="83" />';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='<td align="center" valign="top"';
$body.='style="padding: 0 0 0 20px;">';
$body.='<table width="100%" align="center"';
$body.='cellpadding="0" cellspacing="0"';
$body.='border="0">';
$body.='<tr>';
$body.='<td height="16"';
$body.='style="height: 16px; line-height:16px;">';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="left" valign="top"';
$body.='style="color: #333333; font-family: Arial, sans-serif; font-size: 20px; mso-line-height-rule: exactly; line-height: 24px; font-weight: 400;">';
$body.='Email:';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td height="2"';
$body.='style="height: 2px; line-height:2px;">';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="left" valign="top"';
$body.='style="color: #4eb7fe; font-family: Arial, sans-serif; font-size: 16px; mso-line-height-rule: exactly; line-height:26px; font-weight: 400;">';
$body.='<span style="color: #4eb7fe;"><a';
$body.='style="text-decoration: none; color: #4eb7fe;"';
$body.='href="mailto:info@wheeliesbikes.co.uk">info@wheeliesbikes.co.uk</a></span>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</div>';
$body.='<!--[if (gte mso 9)|(IE)]></td><![endif]-->';
$body.='<!--[if (gte mso 9)|(IE)]>';
$body.='  <td width="440" align="center" valign="top" style="padding: 0 0 0 0;"><![endif]-->';
$body.='<div';
$body.='style="width: 100%; display: inline-block; vertical-align: top; font-size: normal; max-width: 440px;">';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top" style="padding: 0 20px;">';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0"';
$body.='border="0">';
$body.='<tr>';
$body.='<td height="33" style="height: 33px; line-height:33px;">';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="center" valign="top">';
$body.='<table width="100%" align="center" cellpadding="0"';
$body.='cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td width="83" align="center" valign="top">';
$body.='<table width="100%" align="center"';
$body.='cellpadding="0" cellspacing="0"';
$body.='border="0">';
$body.='<tr>';
$body.='<td align="center" valign="top"';
$body.='style="line-height: 0px !important;">';
$body.='<img src="images/icon4.png"';
$body.='alt="icon4" width="83" />';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='<td align="center" valign="top"';
$body.='style="padding: 0 0 0 20px;">';
$body.='<table width="100%" align="center"';
$body.='cellpadding="0" cellspacing="0"';
$body.='border="0">';
$body.='<tr>';
$body.='<td height="16"';
$body.='style="height: 16px; line-height:16px;">';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="left" valign="top"';
$body.='style="color: #333333; font-family: Arial, sans-serif; font-size: 20px; mso-line-height-rule: exactly; line-height: 24px; font-weight: 400;">';
$body.='We are open:';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td height="2"';
$body.='style="height: 2px; line-height:2px;">';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="left" valign="top"';
$body.='style="color: #4eb7fe; font-family: Arial, sans-serif; font-size: 16px; mso-line-height-rule: exactly; line-height: 26px; font-weight: 400;">';
$body.='Mon - Sat: 9:00 AM - 17:30 ';
$body.='</td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td align="left" valign="top"';
$body.='style="color: #4eb7fe; font-family: Arial, sans-serif; font-size: 16px; mso-line-height-rule: exactly; line-height: 26px; font-weight: 400;">';
$body.='Sun - 11:00 AM - 15:00 ';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</div>';
$body.='<!--[if (gte mso 9)|(IE)]></td><![endif]-->';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td height="70" style="height: 70px; line-height:70px;"></td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';

$body.='<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">';
$body.='<tr>';
$body.='<td height="12" style="height: 12px; line-height:12px;"></td>';
$body.='</tr>';
$body.='<tr>';
$body.='<td height="12" style="height: 12px; line-height:12px;"></td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</td>';
$body.='</tr>';
$body.='</table>';
$body.='</body>';
$body.='</html>';