<?php

	$this  ->  m_content_builder  =  "<section class=\"bg-lighter section-66\">";
	$this  ->  m_content_builder  .=  "<div class=\"shell-wide\">";
	$this  ->  m_content_builder  .=  "<div class=\"range range-xs-center text-sm-left\">";
	$this  ->  m_content_builder  .=  "<div class=\"cell-xs-10 cell-sm-8 cell-md-12\">";
	$this  ->  m_content_builder  .=  "<div class=\"range range-xs-center\">";
	$this  ->  m_content_builder  .=  "<div class=\"cell-xs-6 cell-md-3 cell-xl-2\">";
	$this  ->  m_content_builder  .=  "<div class=\"unit unit-spacing-xs unit-sm unit-sm-horizontal\">";
	$this  ->  m_content_builder  .=  "<div class=\"unit-left\"><span class=\"icon icon-xs mdi mdi-phone text-primary\" style=\"font-size: 26px;\"></span></div>";
	$this  ->  m_content_builder  .=  "<div class=\"unit-body\">";
	$this  ->  m_content_builder  .=  "<h6>";
	$this  ->  m_content_builder  .=  "Phone";
	$this  ->  m_content_builder  .=  "</h6>";
	$this  ->  m_content_builder  .=  "<div class=\"p\">";
	$this  ->  m_content_builder  .=  "<a class=\"reveal-block\" href=\"callto:{$m_wheelies_phone_number}\">";
	$this  ->  m_content_builder  .=  $m_wheelies_phone_number;
	$this  ->  m_content_builder  .=  "</a>";

	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "<div class=\"cell-xs-6 cell-md-3 cell-xl-2 offset-top-50 offset-xs-top-0\">";
	$this  ->  m_content_builder  .=  "<div class=\"unit unit-spacing-xs unit-sm unit-sm-horizontal\">";
	$this  ->  m_content_builder  .=  "<div class=\"unit-left\"><span class=\"icon icon-xs mdi mdi-email-open text-primary\" style=\"font-size: 26px;\"></span></div>";
	$this  ->  m_content_builder  .=  "<div class=\"unit-body\">";
	$this  ->  m_content_builder  .=  "<h6>";
	$this  ->  m_content_builder  .=  "E-mail";
	$this  ->  m_content_builder  .=  "</h6>";
	$this  ->  m_content_builder  .=  "<div class=\"p\">";
	$this  ->  m_content_builder  .=  "<a class=\"reveal-block\" href=\"mailto:{$m_wheelies_email}\">";
	$this  ->  m_content_builder  .=  $m_wheelies_email;
	$this  ->  m_content_builder  .=  "</a>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "<div class=\"cell-xs-6 cell-md-3 cell-xl-2 offset-top-50 offset-md-top-0\">";
	$this  ->  m_content_builder  .=  "<div class=\"unit unit-spacing-xs unit-sm unit-sm-horizontal\">";
	$this  ->  m_content_builder  .=  "<div class=\"unit-left\"><span class=\"icon icon-xs mdi mdi-map text-primary\" style=\"font-size: 26px;\"></span></div>";
	$this  ->  m_content_builder  .=  "<div class=\"unit-body\">";
	$this  ->  m_content_builder  .=  "<h6>";
	$this  ->  m_content_builder  .=  "Address";
	$this  ->  m_content_builder  .=  "</h6>";
	$this  ->  m_content_builder  .=  "<address class=\"contact-info\">";
	$this  ->  m_content_builder  .=  $m_wheelies_address;
	$this  ->  m_content_builder  .=  "</address>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "<div class=\"cell-xs-6 cell-md-3 cell-xl-2 offset-top-50 offset-md-top-0\">";
	$this  ->  m_content_builder  .=  "<div class=\"unit unit-spacing-xs unit-sm unit-sm-horizontal\">";
	$this  ->  m_content_builder  .=  "<div class=\"unit-left\"><span class=\"icon icon-xs mdi mdi-timelapse text-primary\" style=\"font-size: 26px;\"></span></div>";
	$this  ->  m_content_builder  .=  "<div class=\"unit-body\">";
	$this  ->  m_content_builder  .=  "<h6>";
	$this  ->  m_content_builder  .=  "Open Hours";
	$this  ->  m_content_builder  .=  "</h6>";
	$this  ->  m_content_builder  .=  "<div>";
	$this  ->  m_content_builder  .=  "<p>";
	$this  ->  m_content_builder  .=  "9:00 – 17:30";
	$this  ->  m_content_builder  .=  " Mon – Sat";
	$this  ->  m_content_builder  .=  "</p>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "<p class=\"offset-top-0\">";
	$this  ->  m_content_builder  .=  "11:00 – 15:00 Sun";
	$this  ->  m_content_builder  .=  "</p>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</section>";
?>