<?php
	$this  ->  m_content_builder  =  "<section class=\"section-98 section-sm-110\">";
	$this  ->  m_content_builder  .=  "<div class=\"shell\">";
	$this  ->  m_content_builder  .=  "<h2 class=\"text-bold\">";
	$this  ->  m_content_builder  .=  "Get In Touch";
	$this  ->  m_content_builder  .=  "</h2>";
	$this  ->  m_content_builder  .=  "<hr class=\"divider bg-mantis bg-wheelies\">";
	$this  ->  m_content_builder  .=  "<div class=\"offset-sm-top-66\">";
	$this  ->  m_content_builder  .=  "<div class=\"range range-xs-center\">";
	$this  ->  m_content_builder  .=  "<div class=\"cell-xs-10 cell-md-8\">";
	$this  ->  m_content_builder  .=  "<!-- RD Mailform-->";
	$this  ->  m_content_builder  .=  "<form class=\"rd-mailform text-left\" ";
	// data-form-output=\"form-output-global\"
	$this  ->  m_content_builder  .=  "data-form-type=\"\" method=\"post\" action=\"\">";
	$this  ->  m_content_builder  .=  "<div class=\"range range-xs-center\">";
	$this  ->  m_content_builder  .=  "<div class=\"cell-sm-6\">";
	$this  ->  m_content_builder  .=  " <div class=\"form-group\">";
	$this  ->  m_content_builder  .=  "<label class=\"form-label\" for=\"git-3-mailform-first-name\">First name</label>";
	$this  ->  m_content_builder  .=  "<input class=\"form-control bg-white\" id=\"git-3-mailform-first-name\" type=\"text\" name=\"firstname\" data-constraints=\"@Required\">";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "<div class=\"cell-sm-6\">";
	$this  ->  m_content_builder  .=  "<div class=\"form-group\">";
	$this  ->  m_content_builder  .=  "<label class=\"form-label\" for=\"git-3-mailform-last-name\">Last name</label>";
	$this  ->  m_content_builder  .=  "<input class=\"form-control bg-white\" id=\"git-3-mailform-last-name\" type=\"text\" name=\"lastname\" data-constraints=\"@Required\">";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "<div class=\"cell-sm-6\">";
	$this  ->  m_content_builder  .=  "<div class=\"form-group offset-sm-top-30\">";
	$this  ->  m_content_builder  .=  "<label class=\"form-label\" for=\"git-3-mailform-email\">E-mail</label>";
	$this  ->  m_content_builder  .=  "<input class=\"form-control bg-white\" id=\"git-3-mailform-email\" type=\"text\" name=\"email\" data-constraints=\"@Required @Email\">";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "<div class=\"cell-sm-6\">";
	$this  ->  m_content_builder  .=  "<div class=\"form-group offset-sm-top-30\">";
	$this  ->  m_content_builder  .=  "<label class=\"form-label\" for=\"git-3-mailform-phone\">Phone</label>";
	$this  ->  m_content_builder  .=  "<input class=\"form-control bg-white\" id=\"git-3-mailform-phone\" type=\"text\" name=\"phone\" data-constraints=\"@Required\">";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "<div class=\"cell-sm-12\">";
	$this  ->  m_content_builder  .=  "<div class=\"form-group offset-sm-top-30\">";
	$this  ->  m_content_builder  .=  "<label class=\"form-label\" for=\"git-3-mailform-message\">Message</label>";
	$this  ->  m_content_builder  .=  "<textarea class=\"form-control bg-white\" id=\"git-3-mailform-message\" name=\"message\"></textarea>";
	// data-constraints=\"\"
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "<div class=\"offset-top-24 text-center\">";
	$this  ->  m_content_builder  .=  "<button name=\"contact-submit\" class=\"btn btn-primary btn-wheelies\" type=\"submit\">Submit</button>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</form>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</div>";
	$this  ->  m_content_builder  .=  "</section>";
?>